### ISSUE TITLE
Add explanation of all known non-mob materials. 

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#10]
For starters:
 - entity
 - entity_alphatest
 - slime_outer

**Comment by ckhrysze** [comment]
I would love to know more about this, and would write something up...how would one even get this information? Looking through the vanilla files, I see things like fishing hook, camera, armor stand and arrow...but I don't have any sense for what those mean.

**Comment by AFoxyToast** [comment]
writing
