### ISSUE TITLE
Make the Vanilla Resource and Behavior Pack links more clear

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#11]
The Useful links section could be updated to include links to the Vanilla Resource Pack and Vanilla Behavior pack downloads.

https://aka.ms/resourcepacktemplate
https://aka.ms/behaviorpacktemplate
https://aka.ms/MinecraftBetaResources
https://aka.ms/MinecraftBetaBehaviors

**Comment by Dreamedc2015** [comment]
i have done it
