### ISSUE TITLE
Style Guide (new doc)

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#131]
We should create a style-guide for bedrock development.

**Comment by SirLich** [comment]
Should possibly consume this article into it: https://wiki.bedrock.dev/knowledge/namespaces.html

**Comment by SirLich** [comment]
NO CAPITALS

**Comment by SirLich** [comment]
snake_case is king

**Comment by SirLich** [comment]
name_RP
name_BP

^ Naming convention for the resource pack and behavior pack

**Comment by SirLich** [comment]
split textures by path, not name. 

(good)
boat/blue 
boat/red

(bad)
boat_blue
boat_red

**Comment by SirLich** [comment]
file naming convention:
boat.geo.json
boat.animation.json
boat.animation_controller.json

(maybe?)
boat.entity.rp.json 
boat.entity.bp.json

**Comment by MegaArman** [comment]
Some behavior pack stuff:
"NO CAPITALS ANYWHERE" - game breaking
-naming conventions for items - should they use underscores or not? Mojang isn't consistent here. Currently correcting some bugs bc of this 
-using skins vs variants for game state etc..we've had unintended side effects using skins

some of my beef with the JS examples I see:
-not a good idea to be adding properties to the System object
-never use "this" -it's been unneeded for 5 yrs, use arrow functions
-JS practices and conventions: const vs var etc, probs a linter suggestion would be helpful here
-event handling

**Comment by SirLich** [comment]
All animations for a specific entity should be grouped together into one file!

**Comment by SirLich** [comment]
use proper dot notation:
big.medium.small

Example:
animation.controller.dragon.flying.taking_off

NOT animation.controller.dragon_take_off_flying

**Comment by SirLich** [comment]
Never use `minecraft` as a namespace.

**Comment by SirLich** [comment]
Organize events and component groups to have complementary names:

Group:
sirlich:wild
sirlich:tame

events:
sirlich:become_wild
sirlich:become_tame

**Comment by SirLich** [comment]
Organization (maybe too opinionated)

Description
Components
Component groups
Events

**Comment by SirLich** [comment]
Always include everything you can in the .lang files, especially description/title, entity names, etc.

**Comment by SirLich** [comment]
Functions should be nested:

YES:
teleport/levels/level_1

NOT:
teleport_lvl1

**Comment by MegaArman** [comment]
> file naming convention:
> boat.geo.json
> boat.animation.json
> boat.animation_controller.json


I'd probs do shorter names for the type of json file and would prefer the animation vs. animation_controller to be more distinct so I can keep my file explorer/sidebar in my editor narrower:
-  boat.geo.json
-  boat.animation.json
-  boat.ctrl.json

Or even:
-  boat.g.json
-  boat.a.json
-  boat.ac.json

The caveat is that if some day mojang adds another directory starting with the same letter, naming may get harder to differentiate

> (maybe?)
> boat.entity.rp.json
> boat.entity.bp.json

Meh- I usually don't find myself working on both bp and rp simultaneously so it's been alright to do "boat.entity.json" . If I do work on both simultaneously I might prefer to have an editor window for each

**Comment by MegaArman** [comment]
Naming tags or scoreboard objectives based on in game entities or items:
-use the actual item name but all lowercase and replace spaces with underscores

For example, consider bone meal in Bedrock:
https://minecraft.gamepedia.com/Bone_Meal#Data_values
```
Name	    Namespaced ID	Numeric ID             Translation key
Bone Meal   dye	                351                    item.dye.white.name
```
If you wanted to do something with the scoreboard if there's bone meal on the ground, write something like:
execute @e[type=item,name="Bone Meal"]  ~ ~ ~ scoreboard players add @s bone_meal 1

Using the item name but lowercase and underscores for spaces is clearer to read in one command than using Namespaced ID, Numeric ID or Translation Key

**Comment by SirLich** [comment]
> 
> 
> > file naming convention:
> > boat.geo.json
> > boat.animation.json
> > boat.animation_controller.json
> 
> I'd probs do shorter names for the type of json file and would prefer the animation vs. animation_controller to be more distinct so I can keep my file explorer/sidebar in my editor narrower:
> 
>     * boat.geo.json
> 
>     * boat.animation.json
> 
>     * boat.ctrl.json
> 
> 
> Or even:
> 
>     * boat.g.json
> 
>     * boat.a.json
> 
>     * boat.ac.json
> 
> 
> The caveat is that if some day mojang adds another directory starting with the same letter, naming may get harder to differentiate
> 
> > (maybe?)
> > boat.entity.rp.json
> > boat.entity.bp.json
> 
> Meh- I usually don't find myself working on both bp and rp simultaneously so it's been alright to do "boat.entity.json" . If I do work on both simultaneously I might prefer to have an editor window for each

Files are rarely created, therefore the opportunity cost of a longer name is very *small*. The focus on a naming convention should be about readability and maintainability -NOT ease of writing. 

This also closely follow the VBP, which is helpful

**Comment by SirLich** [comment]
entity names should be sub-indexed with dots:

sirlich:ship.sailboat

**Comment by MegaArman** [comment]
> Files are rarely created, therefore the opportunity cost of a longer name is very _small_. The focus on a naming convention should be about readability and maintainability -NOT ease of writing.
> 
> This also closely follow the VBP, which is helpful

Eh I forgot about the VBP... I'd either follow it exactly or not at all. 

I agree that readability for pretty much anything is > ease of writing, but making the file/schema type more explicit like "animation_controller" doesn't add readability vs. "ac". It would be akin to writing javascriptobjectnotation instead of json (not to be a smartass here). The longer names are harder to see in sidebars or tabs in editors and in CLIs, which is my gripe with them.

 I'm still on the fence when it comes to naming in bp vs rp though

**Comment by Edacth** [comment]
cat.e - entity file (BP)
cat.ce - client entity (RP)
My style for differentiating the entity files.

**Comment by DaanV2** [comment]
> file naming convention:
> boat.geo.json
> boat.animation.json
> boat.animation_controller.json
> 
> (maybe?)
> boat.entity.rp.json
> boat.entity.bp.json

No need, Resourcepack entities are defined in the folder entity
while behaviourpack entities are defined in the folder entities

**Comment by SirLich** [comment]
> 
> 
> > file naming convention:
> > boat.geo.json
> > boat.animation.json
> > boat.animation_controller.json
> > (maybe?)
> > boat.entity.rp.json
> > boat.entity.bp.json
> 
> No need, Resourcepack entities are defined in the folder entity
> while behaviourpack entities are defined in the folder entities

The reason I created this Issue (instead of just writing it myself) is cause I didn't want it to be sirlich-centric. Just cause I prefer one way doesn't mean it should be written into the style guide. 

With that said, I do actually feel its nice to show the RP and BP separately in file names. I often have files open in an editor like VSCode, and along the top it only shows file name -not path. Identically named files with different functions make this a bit annoying.

boat.entity.json
boat.entity.json 

Which is the file you are looking for?

Would love more feedback from others!

**Comment by SirLich** [comment]
Sort of already added above, but want to put it here again: No Spaces Anywhere. 

I don't want to see any spaces in any file path. That includes the name of the behavior pack and resource pack.

**Comment by SirLich** [comment]
Lowercase name for all files and folders

entities/npc/introduction

NOT

entities/NPCS/Intoduction

**Comment by MegaArman** [comment]
_Don't group items together in a single pool in a loot table_

loot tables use weights so if you have 2 items and want each to have a 50% chance of dropping you might be inclined to do something like
```
{
    "pools": [
        {
            "rolls": 1,
            "entries": [
                {
                    "type": "item",
                    "weight": 1,
                    "name": "minecraft:coal"
                },
                {
                    "type": "item",
                    "weight": 1,
                    "name": "minecraft:diamond"
                },
                {
                    "type": "item",
                    "weight": 1,
                    "name": "minecraft:"
                }
            ]
        }
    ]
}
```
^ I really don't think this is a good way however because say you add another item but  want to keep the previous ones at the same %... You'd have to tweak all the previous items weights since they're grouped together...

Instead you can use empty items like so:
```
{
    "pools": [
        {
            "rolls": 1,
            "entries": [
                {
                    "type": "item",
                    "weight": 50,
                    "name": "minecraft:coal"
                },
                {
                    "type": "empty",
                    "weight": 50
                }
            ]
        },
        {
            "rolls": 1,
            "entries": [
                {
                    "type": "item",
                    "weight": 50,
                    "name": "minecraft:diamond"
                },
                {
                    "type": "empty",
                    "weight": 50
                }
            ]
        }
    ]
}
```

Yes, it's a lot more JSON but keeping the item probabilities "separate" in this way allows for easy modification. The numbers for the weights are now used as %. If you wanted to change the percent of diamond to be 25%, simply change its weight to 25 and the following empty's weight to 75.

There's always loot table generators to speed-up the writing. It took less than a few min to create the above examples with
https://amaury.carrade.eu/minecraft/loot_tables
