### ISSUE TITLE
Minecraft Directories/Folders Guide 

### ISSUE THREAD

**Issue by MegaArman** [SirLich/technical-bedrock#134]
A doc to explain the differences between minecraft directories/folders such as development_behavior_packs & development_resource_packs vs. the minecraftWorlds/_hash_thingie_/behavior_packs minecraftWorlds/_hash_thingie_/resource_packs vs. the com.mojang/behavior_packs

Also, an example workflow for working on an existing project when given only a world file:
1. download the world file
2. deactivate bp and rp in game ?
3. manually delete both packs from the minecraftWorld (the levelname.txt tells which world is which)
4. download (clone from a git repo if you use it) the behavior and resource packs into the development_behavior_packs and development_resource_packs 
5. activate packs again?

the ? is because I don't know if those steps are necessary

**Comment by SirLich** [comment]
Hmm. I think this could go well as part of #132

**Comment by SirLich** [comment]
@MegaArman I am going to close this for now. It feels very marketplace centered, which isn't necessarily the goal of the wiki. We can revisit it once we find somewhere meaningful for it to go.
