### ISSUE TITLE
hello_world for marketplace example bp & rp

### ISSUE THREAD

**Issue by MegaArman** [SirLich/technical-bedrock#135]
I've been gradually making a hello_world type bp and rp with an example for each of the files/features the marketplace currently supports (animations, functions, etc.). I could make it conform to the style guide after we complete it (https://github.com/SirLich/bedrock-wiki/issues/131)

**Comment by SirLich** [comment]
I wonder what the best way to go about this is 🤔 

I mean we can definitely host .zip files for download.

**Comment by MegaArman** [comment]
they're on github which actually hosts zips now. Clicking the "Code" button on a repo page will show a dropdown with a link to the zip

**Comment by SirLich** [comment]
@MegaArman Do you want to tackle this? Looking to clean out the back-log.

**Comment by SirLich** [comment]
@MegaArman this is being closed out, due to the fact that we now have natively supported Guide packs.
