### ISSUE TITLE
Example flipbook texture is incorrect width

### ISSUE THREAD

**Issue by t3hero** [SirLich/technical-bedrock#178]
Prodvided flipbook texture on 

https://guide.bedrock.dev/-/blocks-flipbooks

For

https://lh4.googleusercontent.com/rHei2u4VsKQiNPdMzdU6Kx5ToEvf6WZYggAz4Oyryp1bcKLuKb7I6S-V-SfbQT6QtP2sy212k3ecRUP8IEIdk18EHM2ByKtwCPGzR6d-27wSm4Olt48=w1280

Is 15 width, rather than the suggested 16 width

**Comment by SirLich** [comment]
@KaiFireborn is this something you could tackle? I don't know anything about flipbooks.

Otherwise @t3hero if you are willing/able to provide use updates assets that would be helpful.

**Comment by KaiFireborn** [comment]
It should be correct. I'm going to check the files again. By the way, we already have that image here on github, no Google Photo references are needed

**Comment by KaiFireborn** [comment]
Update: I fixed that image resolution, thanks for reporting this! I'll close this issue
