### ISSUE TITLE
/tellraw capabilities in bedrock doc

### ISSUE THREAD

**Issue by KaiFireborn** [SirLich/technical-bedrock#179]
Most of the information about /tellraws and /titleraws is mixed between bedrock and Java -  a well organized Bedrock-specific article would be useful

**Comment by SirLich** [comment]
Should go in the documentation section. Suggested format:

# What is tellraw

### simple explanation

### compared to java

# Format

### Exact format information

# Examples

### Specific examples

**Comment by Dreamedc2015** [comment]
[Started and finished](https://github.com/SirLich/bedrock-wiki/pull/222)
