### ISSUE TITLE
Update texture layering doc

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#18]
The texture layering doc needs a paragraph talking about materials, and their properties. In particular, the required texture is `villager_v2_masked`.

**Comment by SirLich** [comment]
Also talk about geometry

**Comment by Hatchibombotar** [comment]
Texture layering doc is now moved to [the render controller doc](https://wiki.bedrock.dev/concepts/render-controller#texture-layering)

**Comment by SirLich** [comment]
Closed
