### ISSUE TITLE
Investigate porting json UI documentation over

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#180]
Here is the link: https://github.com/bleonard252/mc-addon-resources

Please note the CC-BY license. We will need to make a note of this when porting over. 

Should we even port over? Can somebody look into this?

**Comment by PepijnMC** [comment]
Although the JSON UI system is currently how you would modify UI and thus probably something you would want some documentation on, with some of the sneak peeks we got into scripting this UI system is going to be faded out in favor of a new HTML UI system. When this happens I wouldn't know and I'm not saying to NOT document this older system, but if we do I think it should include some kind of warning that this entire JSON UI system is considered deprecated.

I might just write something of my own. I know the system decently well and I feel just doing it from scratch is going to take me less time than trying to adapt Bleonard's guide. Bit low priority for me though, as I don't advise anyone to use this old system unless they really can't wait to modify UI.

**Comment by SirLich** [comment]
@PepijnMC I am a fan of the iterative process. If you wanted to tackle a "2 minute explanation + disclaimer" doc, with a link perhaps to Bleonards guide, that could be good enough. 

Especially like you said if the UI stuff is being phased out for a newer system.

**Comment by SirLich** [comment]
This has been done. See page here: https://wiki.bedrock.dev/concepts/json-ui
