### ISSUE TITLE
[Guide] Merge duplicates (final step)

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#181]
After the guide is merged in completely, we will want to do some work integrating it better into the wiki. This includes moving pages from the wiki into the guide, and possibly visa-versa. 

I think the Guide is served best as a step-by-step, while more general documentation is kept outside. Although this could definitely be argued against! 

In particular, there are sections like "shortnames" (items doc) which are currently being blazed over with almost no explanation. Either we need docs in the wiki explaining the concept, and a link from the guide, or the guide needs to be improved in that location.

**Comment by SirLich** [comment]
Potential conflict pages:
- The editor section (merge into guide)
- The getting started section (remove wiki version)
- The useful links section (remove guide version)

Probably more.

**Comment by KaiFireborn** [comment]
I'll do this along with standardizing the Subguide formatting. Much will have to be discussed with @SirLich .

**Comment by KaiFireborn** [comment]
Completed
