### ISSUE TITLE
Create a feature document for upcoming technical changelogs.

### ISSUE THREAD

**Issue by PepijnMC** [SirLich/technical-bedrock#206]
Bedrock changelogs are pretty lackluster compared to Java's when it comes to technical changes and additions. A document with a proper and easy to understand technical changelog for the next update (in this case 1.16.100) would be helpful for anyone trying to keep up with new features. Notes on what features are in experimental (and when they leave experimental) are also very helpful.

**Comment by stirante** [comment]
I think it would be a good idea to use recently created news page for this. I already thought about posting about newest betas, but with emphasis on technical changes and how we could use them.

**Comment by stirante** [comment]
Added news tag: https://wiki.bedrock.dev/news/bedrock-betas.html

Also first changelog written by me (I had no idea what to write about bugfix version honestly): https://wiki.bedrock.dev/2020/10/16/beta-1-16-100-60.html

**Comment by SirLich** [comment]
I'm closing this out. Thanks for the suggestion Pepijn, and thanks to Stirante for making the implementation!
