### ISSUE TITLE
Create sidebar widget for marking BETA content

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#210]
Not sure whether its better to be generic, or hard-coded as BETA. 

The style match should be equivalent to the existing widgets in the theme.

Example: https://discord.com/channels/494194063730278411/713856400631267369/766614845218750475

Can we make it based on some front-matter in the post? Would be nice if we didn't have to edit the sidebar directly. Maybe a field like:

 - widget: 
     text: BETA
     color: blue

I know nothing about Jekyll though. If this is tough, probably don't worry about it.

**Comment by stirante** [comment]
Added in https://github.com/SirLich/bedrock-wiki/commit/b212b67c3fba091940bd03b6f2e32969b605baf0
