### ISSUE TITLE
[Guide] Change `res` to `RP`

### ISSUE THREAD

**Issue by KaiFireborn** [SirLich/technical-bedrock#228]
WARNING: `res` often appears in normal words (like `resources`) which is why it cannot be replaced automatically, unlike `bhv`, which I already did.

**Comment by SirLich** [comment]
May be able to search for `res/` 

I think its not too much work to skim through though.

**Comment by KaiFireborn** [comment]
There is also stuff like "res folder" there, in which case it wouldn't work. There's also "textu`res/`" paths, which absolutely forbids such a search. It might not be that much work, and someone can do it, that's why I made it an issue.

**Comment by ReverendQ** [comment]
I went ahead and did a text search for `res/`, I found:

- `assets\guide\template_packs\kf-Tutorial res\textures\flipbook_textures.json` (at the top, commented out)
- `guide\custom-items.md` (Under the "Setting Item Names" section

Everything else I could find is either part of the word "textures" or part of the file path of the "kf-Tutorial res" template pack.
