### ISSUE TITLE
Maybe remove signatures from bottom of pages 

### ISSUE THREAD

**Issue by Dreamedc2015** [SirLich/technical-bedrock#230]
I find it looks a bit weird and isn't consistent across pages 
[this one](https://wiki.bedrock.dev/tutorials/disabling-particles.html#original-author-ambient)
[another](https://wiki.bedrock.dev/tutorials/cancelling-death-animations.html#credits)
[and another](https://wiki.bedrock.dev/tutorials/controlling-flying-entities.html#original-author-assassin-assassin1634-4242020)
[and at the bottom of this one](https://wiki.bedrock.dev/tutorials/remove-shadows.html)
are some examples I have seen feel it would be better suiting to not to sign

**Comment by stirante** [comment]
I don't think it would be fair to the authors. Better would be to make them more consistent. To credit people working on wiki I added a contributors section at the bottom of every page, but sometimes it's just who added it to the wiki and not who wrote it.

**Comment by Dreamedc2015** [comment]
I do agree that people working on the pages should be credited but the system at the bottom of the pages with the profile icons and links is cleaner than people's random signatures at the bottom of the wiki making it seem allot less clean

**Comment by SirLich** [comment]
![image](https://user-images.githubusercontent.com/18729296/96694117-5061d180-1388-11eb-8538-7002f71befe5.png)
I especially hate that it shows in the side bar. 

I am personally comfortable removing all "personal credit" markdown, especially if the user appears in the contributors list. 

I am NOT comfortable removing "original source" links (like things I found on reddit or whatever).

**Comment by Dreamedc2015** [comment]
that's what I'm saying it looks ugly and disorganized
