### ISSUE TITLE
Beginners Guide: Getting Started page doesn't exist

### ISSUE THREAD

**Issue by abrightmoore** [SirLich/technical-bedrock#262]
On this page:

https://github.com/SirLich/bedrock-wiki/tree/gh-pages/guide

The link at the end of this section is busted - target page not yet written? Consider removing the link:

You will make your first steps in creating an add-on here, by learning to create manifests and pack_icons (a.k.a initializing an Add-On), as well as learn to use some of the .mc file extensions. No previous coding experience required. After you’ll create a testing World where you’ll be able to test the first feature of your add-on - a custom /function. We’ll also learn about transpiling Add-ons and other .mc file extensions.

[Getting Started](https://wiki.bedrock.dev/guide/getting-started.html)

**Comment by SirLich** [comment]
Thanks for the issue. This relates to: #254 

There are still some growing pains in getting the guide converted over, so thanks for letting us know!
