### ISSUE TITLE
Beginner's Guide link to tutorial RP and BP doesn't allow direct download of the packs

### ISSUE THREAD

**Issue by abrightmoore** [SirLich/technical-bedrock#263]
GitHub doesn't support downloading only a single folder unless using community tools. It would be better to have a pre-zipped RP and BP archive to remove this complication for beginners.

Source page:
https://wiki.bedrock.dev/guide/

Source text:
Note: A template Add-On, containing all code examples from this guide can be downloaded [here](https://github.com/SirLich/bedrock-wiki/tree/gh-pages/assets/guide/template_packs).

Sample RP and BP link location:
https://github.com/SirLich/bedrock-wiki/tree/gh-pages/assets/guide/template_packs

**Comment by SirLich** [comment]
Yep, spot on. Feel free to make the edit yourself if you feel comfortable, or somebody will tackle it when we have time. 

I think this also related to this task: #226
