### ISSUE TITLE
What changed in 1.16.100? 

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#265]
Hey guys! Looking to crowd-source information about 1.16.100, which will be turned into a blog-post for the News section. 

what broke?
what was added?
format changes?
what moved from EXP into stable?

Do share :)

**Comment by chickenputty** [comment]
https://wiki.bedrock.dev/tutorials/spawning-items#all-purpose-method

This is broken on 1.16.100 as "drop_item_for" is now undocumented and needs extra parameters to function. We have found that the entity is gone before it gets time to drop. This is kind of patched by increasing movement speed, but not perfect. The best swap for now is "sneeze", but it leaves a nasty particle behind that I believe is redstone based so it can't be removed.

**Comment by GitWither** [comment]
It is now easier than ever to spawn items: simply save an empty structure with an item inside (make sure to save entities) and load that structure with /structure load

**Comment by ambiennt** [comment]
https://github.com/DrAv0011/Bedrock-Template-Updates/compare/1.16.20...1.16.100

**Comment by ghost** [comment]
```
{
	"minecraft:behavior.drop_item_for": {
		"priority": 1,
		"seconds_before_pickup": 0,
		"cooldown": 0.25,
		"drop_item_chance": 0.7,
		"offering_distance": 5,
		"minimum_teleport_distance": 2,
		"max_head_look_at_height": 10,
		"target_range": [
			5,
			5,
			5
		],
		"teleport_offset": [
			0,
			1,
			0
		],
		"time_of_day_range": [
			0.74999,
			0.8
		],
		"speed_multiplier": 1,
		"search_range": 5,
		"search_height": 2,
		"search_count": 0,
		"goal_radius": 1,
		"entity_types": [
			{
				"filters": {
					"test": "is_family",
					"subject": "other",
					"value": "player"
				},
				"max_dist": 6
			}
		],
		"loot_table": "loot_tables/entities/cat_gift.json",
		"on_drop_attempt": {
			"event": "minecraft:cat_gifted_owner",
			"target": "self"
		}
	}
}
```
A new addition has been added for minecraft:behavior.drop_item_for, this include : 
- "seconds_before_pickup": value
- "cooldown": value
- "minimum_teleport_distance": value
- "max_head_look_at_height": value
- "target_range": [ value, value, value ]
- "teleport_offset": [ value, value, value]

**Comment by SirLich** [comment]
Diff viewer: https://github.com/DrAv0011/Bedrock-Template-Updates/compare/1.16.20...1.16.100

**Comment by SirLich** [comment]
Actual changelog: https://feedback.minecraft.net/hc/en-us/articles/360052592091-Minecraft-1-16-100-Bedrock-

**Comment by stirante** [comment]
Description for `drop_item_for`

https://paste.stirante.com/ehawaroquc.hs

**Comment by chickenputty** [comment]
> Description for `drop_item_for`
> 
> https://paste.stirante.com/ehawaroquc.hs

How did you get this? @stirante 

EDIT: Never mind, you answered here: https://discordapp.com/channels/494194063730278411/713856400631267369/778530381393297409

**Comment by pascal541** [comment]
New commands:
- /camerashake
- /clearspawnpoint
- /event
- /fog
- /music
- /playanimation
- /ride
- /structure
- /schedule

**Comment by pascal541** [comment]
New Block and Item components. Custom block geometry. These components are probably still behind experimental gameplay (can't confirm).

**Comment by SirLich** [comment]
> 
> 
> New Block and Item components. Custom block geometry. These components are probably still behind experimental gameplay (can't confirm).

Figuring out whats in EXP, whats in BETA, and whats in STABLE is a big thing I would like to disambiguate.

**Comment by StealthyExpertX** [comment]
Here's the tested format for "run_command" in entity events in behaviors in this update 1.16.100.

**Notes:** 

_1. Experimental needs to be used currently,

2. Commands do not use slashes,

3. Target is used to run the command off that target if no selector provided.

4. Uses [] list for multiple commands for the value of "command"_

```
  "prefix:event_name": {
    "run_command": {
      "command": "say true",
      "target":"self"
    }
  }
```

**Comment by StealthyExpertX** [comment]
Spawn eggs have changed this update of 1.16.100 and they no longer randomly generate a damage value, instead they use this format for give commands and loot tables, trades from my testing the id of a creeper spawn egg is in NBT.

`
minecraft:creeper_spawn_egg
`
**It also works for custom entities after doing a quick test,**
`
prefix:custom_name_spawn_egg
`

**Comment by StealthyExpertX** [comment]
Custom material inheriting is no longer valid and causes content log errors the workaround Is to define the material fully custom with just the prefix and material name.

```json
{
  "materials": {
    "version": "1.0.0",
    "prefix:window_glass:entity": {//now throws a content log error.
      "+states": [
        "Blending"
      ],
      "defines": [
        "ENABLE_FOG",
        "ENABLE_LIGHT",
        "USE_ONLY_EMISSIVE"
      ]
    },
    "prefix:window_glass:": {//corrects the content log error.
      "+states": [
        "Blending"
      ],
      "defines": [
        "ENABLE_FOG",
        "ENABLE_LIGHT",
        "USE_ONLY_EMISSIVE"
      ]
    }
  }
}
```
