### ISSUE TITLE
Bedrock Dedicated Server Page

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#267]
I think it would be cool to have a page on various server hosting solutions:
Some I know of:
 - BDS
 - BDSX
 - Element Zero
 - Nuqit

**Comment by SirLich** [comment]
nukkit and cloudburst-nukkit

**Comment by SirLich** [comment]
Proposed Structure:

1) What are Bedrock Servers

2) What is the BDS?

3) Alternatives

**Comment by SirLich** [comment]
Dragonly

**Comment by Dreamedc2015** [comment]
i shall do this

**Comment by SirLich** [comment]
Can we include discord links, where possible? https://discord.gg/TdSaNnxT

**Comment by SirLich** [comment]
https://wiki.vg/Bedrock_Edition_Program_List

**Comment by SirLich** [comment]
https://discord.com/invite/pC9XdkC

**Comment by SirLich** [comment]
Migrated
