### ISSUE TITLE
Block Texture Variation tutorial seems broken 

### ISSUE THREAD

**Issue by RavinMaddHatter** [SirLich/technical-bedrock#280]
I am not 100% sure on this but it seems the method of block variation method is broken in 1.16.200.
https://wiki.bedrock.dev/tutorials/block-texture-variation

If someone knows how to make it work or what changed i can help update, but for now it should be removed to reduce confusion or at least marked as non fuctional

**Comment by SirLich** [comment]
Good eye. In general, some tutorials got broken in .200, and nobody seems to have time fixing them. 

We should probably remove bloat overall so we can better maintain everything. 

Please feel free to remove the page yourself if you feel capable.

**Comment by RavinMaddHatter** [comment]
PR submitted #282 I updated to a different method, I think this is valuable to keep in the wiki. feel free to close.
