### ISSUE TITLE
What changed in 1.16.200?

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#281]
Same as always. Throw down a list of updates/changes, with an emphasis on add-on-related changes, broken-components, etc.

**Comment by pjerson** [comment]
Shooter, fuel, and fertilizer components are still broken

**Comment by pjerson** [comment]
The dreaded `minecraft:conditional_bandwidth_optimization` component has removed from entities, preventing the awful entity lag

**Comment by pjerson** [comment]
We have `query.cardinal_facing_2d` now

**Comment by Hatchibombotar** [comment]
Created Page. [Link](https://wiki.bedrock.dev/update-1-16-200)     https://github.com/SirLich/bedrock-wiki/commit/4b0dbbab9bc4c27c86d74a7c1d7c8e0204620c95
