### ISSUE TITLE
initialize and pre_animation 

### ISSUE THREAD

**Issue by MegaArman** [SirLich/technical-bedrock#304]
```
        "initialize": [
          "variable.x= 0;"
        ],
        "pre_animation": [
          "variable.x= query.is_on_ground == 1 ? 0 : variable.x + 0.5;"
        ],
```

I haven't seen documentation on `initialize `or `pre_animation`, but from seeing their usage in the scripting discord and trying them out, `initialize `seems to set variables when the entity first exists and then `pre_animation `seems to execute the statements it contains before any animation.

There's an example here https://wiki.bedrock.dev/tutorials/custom-item-models#render-controller 
Perhaps the explanations should go in this tutorial.. unsure

**Comment by MedicalJewel105** [comment]
Should be in new MoLang section I guess
