### ISSUE TITLE
Fix RP and BP folder schema

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#313]
The BP version is gone for some reason. Search through GitHub history -it may have gotten deleted when moved (move, but not added again).

Otherwise create from scratch.

Also both versions need to be updated to use the Folder Tree Viewer Stirante wrote. You should leave the path information in a comment at the top of the page so we can regenerate as needed.

**Comment by stirante** [comment]
https://github.com/SirLich/bedrock-wiki/commit/c81bd7ffb1ffd40d7061cbc8d69b3ad0d07550b8

Done. CSS might take a while to update.
