### ISSUE TITLE
Emoji update!

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#326]
https://discord.com/channels/523663022053392405/787594834151604224/802037150790320149

**Comment by Hatchibombotar** [comment]
https://github.com/SirLich/bedrock-wiki/commit/4f864e115582ecace5fa52fcf05156ea8083e450

**Comment by stirante** [comment]
Provided images are only a guide for hex codes. Here are clean ones:
https://cdn.discordapp.com/attachments/787594834151604224/802487359564021760/glyph_E0.png
https://cdn.discordapp.com/attachments/787594834151604224/802487361019052032/glyph_E1.png

Also needs to mention, that the characters range from 0xE000 to 0xE0FF for first image and from 0xE100 to 0xE1FF for second image and to convert number to unicode character, we can use this site: https://r12a.github.io/app-conversion/

Images also should be on separate line.

Unless someone fixes that earlier, I'll try to fix that later today.

**Comment by SirLich** [comment]
Did you see my additional stuffs in the discord thread? Its worth mentioning the images can be scaled to higher resolutions, although that will also scale existing glyphs, unless you scale them down.

I think... I think thats all? Its worth skimming over the thread again -Mitchel provided some good info!

**Comment by StealthyExpertX** [comment]
Here's a thought/idea of an explanation if somebody else wanted to break it down / simplify it further go ahead :)


Once you have emojis inside of the **glyph_E0.png** or **glyph_E1.png** you need to find your character in a hex.

Example of a character as hex: **0xE102**
Example of the character range in hex: **0xE000** to **0xE1FF**

First, always add **0x** at the beginning then add the id of your **glyph_E1.png** the id of this file we are using is **E1**

We have **0xE1** now add the slot id of your **glyph_E1.png** it should look like this **02** to the end of our hex character which now looks like **0xE102**

A brief explanation: The **0** is the row id **0-9** through **A-F**
so **A2** would be the second row and third column in the **glyph_E1.png**

So after your done, it will look like **0xE102** and convert the hex into a character you can simply copy and paste your hex on a website like unicodelookup.com or for more advanced creators r12a.github.io/app-conversion

**Comment by stirante** [comment]
I improved it a bit https://github.com/SirLich/bedrock-wiki/commit/fc97b1b1495f0ab23429aa4fda5557e402fe2a55
Let me know whether it's ok now.

**Comment by StealthyExpertX** [comment]
Looks great so far!
