### ISSUE TITLE
Troublshooting page for items

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#334]
This would be in the same style as entity troubleshooting doc, just for items instead. Talk about 1.10 Vs. 1.16 items. Show common issues like item texture not working, etc

**Comment by SmokeyStack** [comment]
1.10 vs 1.16 Items
Learn about new items here: https://wiki.bedrock.dev/concepts/items

Items are VERY DIFFERENT in 1.16. The main change you need to focus on is that there are longer two files (BP + RP), but rather a single BP file. This means that components like the following need to go into the BP -not the non-existent RP file.

```
"minecraft:icon": {
    "texture": "copper_ingot"
}
```
___
My textures are missing!
Calm down, navigate to your item_texture.json. Ensure that it is properly named. Navigate to your item file. If it uses 1.16, make sure its
```
"minecraft:icon": {
    "texture": "your_texture_name"
}
```
Make sure it matches the one from your item_texture.json
____
My item is huge when using the new render_offset for 1.16.100!
To turn it into a 16x16, use the following formula provided by || MajestikButter ||#3362, ```base value/(res/16)```

[0.075, 0.125, 0.075] seems to be the about the same scale value as normal items

**Comment by Kas-tle** [comment]
@SmokeyStack If this is something you'd like to address feel free to open a pull request with your proposed changes on this repository, editing the `gh-pages ` branch. If you're unfamiliar with the process, you can refer to the [GitHub Docs](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request), or join the [Bedrock OSS Discord](https://discord.gg/XjV87YN
) for further assistance. Thanks for taking an interest in helping out.
