### ISSUE TITLE
Useful Links: manifest generator update

### ISSUE THREAD

**Issue by alexandre97costa** [SirLich/technical-bedrock#335]
Hi, i've noticed that the current manifest generator present in the wiki links is outdated, so I made my own on https://bedrock-manifest.web.app/

I'm suggesting reviewing my project and have it replace the current one

**Comment by SirLich** [comment]
Hey! We are looking into this at the moment. There are a lot of generators, and we are still deciding internally how we want to handle it.

**Comment by SirLich** [comment]
Added

**Comment by alexandre97costa** [comment]
Thanks!

SirLich <notifications@github.com> escreveu no dia domingo, 28/02/2021 à(s)
14:07:
