### ISSUE TITLE
Create sounds page to match particles/fog page

### ISSUE THREAD

**Issue by Hatchibombotar** [SirLich/technical-bedrock#340]
Create sounds page https://minecraft.gamepedia.com/Sounds.json/Bedrock_Edition_values to match https://wiki.bedrock.dev/documentation/particles

**Comment by SirLich** [comment]
What about this existing page: https://wiki.bedrock.dev/documentation/sound-definitions

Also the one on Gamepedia looks really nice. Do we really want to duplicate this work, or just let them handle it?

**Comment by Hatchibombotar** [comment]
Must have missed it! Page looks good and there is no reason to copy a page. Close this issue?

**Comment by Snufie** [comment]
Maybe update the page to match 1.16.201??
