### ISSUE TITLE
Entity Movement update

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#343]
Quite a lot of updates needed here. 

1. Make everything links
2. Add description column where its missing
3. Make the "preferred path" into its own section
4. Add the rest of the moving behaviors (rn just has two)

**Comment by Snufie** [comment]
Wouldn’t it be good to add a few examples of how to document each component? To build on bedrock.dev’s documentation with extra examples on the wiki on how to use the components?
