### ISSUE TITLE
Troubleshooting page for blocks

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#351]
We need a troubleshooting page for blocks, that follows the same general flow as the Entity troubleshooting page. It doesn't necessarily need to be step-by-step, but it should show the common content log errors, as well as tips-or-tricks for making sure your blocks are working as expected. 

It should help somebody both new and experienced with blocks troubleshoot their issue.

**Comment by SmokeyStack** [comment]
Rough draft of [Blocks troubleshooting page](https://gist.github.com/SmokeyStack/3a9842b8ab1596057842b07fd66fe5dc)

**Comment by SirLich** [comment]
Done
