### ISSUE TITLE
Add experience levels as a standard to pages

### ISSUE THREAD

**Issue by Snufie** [SirLich/technical-bedrock#353]
Every page in Concepts, Knowledge, Scripting and Tutorials should have an experience label;
- Starter (people that just started out, this is basically child’s play type of easy)
- Novice (used to be: Beginner; people that have good experience with the basics and essentials)
- Experienced (used to be: Intermediate; people that know a lot about creating addons, basically the level at which you can help beginners and other experienced users out)
- Expert (used to be: Advanced; people that are familiar with even the hardest subjects of creating addons, basically people that can write addons with ease and rarely have to ask stuff, stuff with this label is not understandable for starters and hard to understand for beginners)

Colors for each label:
- Starter
   - Light grey with black text
- Novice
   - Vibrant dark green with white text
- Experienced
   - Orangey or Goldish yellow with black text
- Expert
   - Vibrant dark crimson with bright magenta-pink-ish text

**Comment by SirLich** [comment]
A few notes:
 - We are already sort of doing this, with Beginner, Intermediate, and Advanced. Green -> Yellow -> Red.
 
 I would rather keep with this style for a few reason:
 1) We are already using it
 2) It doesn't require adding new SCSS colors
 3) It looks good on both light-mode, and dark-mode themes
 
 ---
 
 Also worth nothing: We can actually use these categories as sub-headings inside of the actual page. For example starting with a beginners explanation, and then having some intermediate or advanced areas bellow. This is currently already being done.

---

So yeah, good issue overall. I would definitely support adding more difficulty-level pips around the wiki. Just I don't think we need a NEW entire paradigm, and I'm sorta against cluttering things with new colors.

**Comment by Snufie** [comment]
Yes it was a little far fetched but it is quite nice to atleast change the names and add a starter level.
___
I did not plan to make the labels appear in the titles of pages. But as labels inside the page, as they appear currently.
___
Adding them as a necessity to each page will give the wiki a more organized feel and clear up some misconceptions and underestimations about the difficulty of subjects.

**Comment by SirLich** [comment]
> but it is quite nice to atleast change the names and add a starter level.

I don't think we should change names/color or add a "starter" label. 

Three labels is clean, organized, and follows the accepted flow for color difficulty (green easy, yellow medium, red hard). We can vote on this in the discord though, if you insist.

---

I am definitely in support of adding these labels everywhere on the wiki to make it consistant tho

**Comment by SirLich** [comment]
Migrated
