### ISSUE TITLE
Guide Updates and Issues

### ISSUE THREAD

**Issue by Hatchibombotar** [SirLich/technical-bedrock#354]
The beginners guide is long overdue for an update. This issue is to collect all of the issues and things to update with the beginners guide. The update should only be made once the 1.16.100 block format (currently in experimental) gets fully released. I will update the list below with any changes that should be made.

**Changes that need to be made**
- [ ] Fix wrong paths in [Loot tables page](https://wiki.bedrock.dev/guide/loot_tables-recipes-spawn_rules#custom-loot-tables)

**Comment by SirLich** [comment]
I think that small stuff can be tackled before the new content drops. Obviously the blocks/items will need a full rewrite at that point.

**Comment by SirLich** [comment]
Closed due to 2.0
