### ISSUE TITLE
Some minor things which I understand as mistakes

### ISSUE THREAD

**Issue by IlkinQafarov** [SirLich/technical-bedrock#357]
![Screenshot_2021-03-08-02-14-07-412_com sec android app sbrowser](https://user-images.githubusercontent.com/73022080/110256806-5dd4cc80-7fb4-11eb-9075-9d2e1b91c9f0.jpg)
![Screenshot_2021-03-08-02-14-19-974_com sec android app sbrowser](https://user-images.githubusercontent.com/73022080/110256811-60cfbd00-7fb4-11eb-8d42-4109b627e23d.jpg)

As you can see, maybe you forgot to put link to subguide, and you didnt write down "o" letter in sheep controller sentence.

**Comment by SirLich** [comment]
Hi. Thank you for the report.

In the future, can you try and use text? Its quite difficult to know where the issues are. 

The guides are in a constant state of improvement... we will try to fix these issues when we can.

**Comment by Kas-tle** [comment]
Resolved by f09396e.
