### ISSUE TITLE
Some form of collapsibles

### ISSUE THREAD

**Issue by Snufie** [SirLich/technical-bedrock#364]
There isn’t much I can explain about this.
Sometimes code blocks are too long and take up a majority of the page, vanilla usage also has such a big list that it causes the page to reload due to lag and high ping. If there is some form of collapsible in markdown or like that, using it will be useful for improving user friendliness and readability.

**Comment by SirLich** [comment]
We do have something for colapsables. They don't look amazing, but you can see them in-action on the first sub-guide. There is one for VSCode extensions.

It won't help with the load issue, since I do believe hidden contents stull fully load tho

**Comment by SirLich** [comment]
Closing: Done for Wiki 2.0
