### ISSUE TITLE
two docs on JSON UI

### ISSUE THREAD

**Issue by mrpatches123** [SirLich/technical-bedrock#400]
https://wiki.bedrock.dev/json-ui and https://wiki.bedrock.dev/json-ui. 
![Screenshot (781)](https://user-images.githubusercontent.com/49619048/118280854-956f6180-b49a-11eb-9b35-0c27561a8311.png)

**Comment by SirLich** [comment]
Thanks for the report! Thats wacky haha!

We actually have a third, although its under documentation section, and has different format: https://wiki.bedrock.dev/documentation/json-ui

Thanks for the report!

**Comment by Kas-tle** [comment]
Resolved by ba78e4d.
