### ISSUE TITLE
Add doc on renaming/retexturing vanilla items

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#50]

**Comment by seriousa1** [comment]
Working on it.. eta end of week

**Comment by Dreamedc2015** [comment]
thou shall beat you seriousa1

**Comment by Dreamedc2015** [comment]
> Working on it.. eta end of week

thou shall beat you seriousa1

**Comment by SirLich** [comment]
Either of you still planning on writing this?? haha
