### ISSUE TITLE
Implement 1.16 changelog

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#52]
Most attack goals are now data-driven
Most Slime and swim goals are now data-driven
Experience Orbs have been data-driven
Fireballs have been data-driven
Elytra have been data-driven
NPC geometry and animations have been data-driven
Tree generation is now data-driven
Drowned are now data-driven
Wither skull attacks are now data-driven
Item sprites are now data-driven

**Comment by SirLich** [comment]
Map color definition changed to "minecraft:map_color": "#FFFFFF",

**Comment by KaiFireborn** [comment]
Block component definition simplified: here's how a new custom block behavior file
 might look like:
```json
{
    "format_version": "1.12.0",
    "minecraft:block": {
        "description": {
            "identifier": "jdot:sapphire_block",
            "is_experimental": false,
            "register_to_creative_menu": true
        },
        "components": {
            "minecraft:loot": "loot_tables/blocks/sapphire_block.json",
            "minecraft:destroy_time": 3,
            "minecraft:explosion_resistance": 3,
            "minecraft:friction": 0.9,
            "minecraft:flammable": {
                "flame_odds": 0,
                "burn_odds": 0
            },
            "minecraft:map_color": "#FFFFFF",
            "minecraft:block_light_absorption": 0,
            "minecraft:block_light_emission": 0.250
        }
    }
}

**Comment by KaiFireborn** [comment]
Models that have more than one locator [with the same name], e.g `lead` will now return an error, which wasn't previously the case.

**Comment by JannisX11** [comment]
> Models that have more than one locator [with the same name], e.g `lead` will now return an error, which wasn't previously the case.

Also the case if you use multiple geometries that each have the same locator. This is considered invalid, each locator must be unique in an entity.

**Comment by SirLich** [comment]
Need more info about this, but it appears timer components "looping" status has changed from a string to a boolean.

**Comment by FETXU** [comment]
> Need more info about this, but it appears timer components "looping" status has changed from a string to a boolean.

I can confirm that timer now takes a boolean value. Tested in 1.16.0 build 4211827

**Comment by Piki-Studios** [comment]
I am finding that I need to add the "leashable" componant to any entity I want to tp to the void. I have tried with my custom entities on 1.16.0

**Comment by SirLich** [comment]
100%, I tested already, custom blocks/items and structure blocks not experimental anymore

**Comment by SirLich** [comment]
custom recipes are out of experimental

**Comment by SirLich** [comment]
1. Check your ping to a server, thats how much time you have
2. Go on that server
3. You have to press e twice within your ping, see step 1
4. Minecraft crashes
I literally only just downloaded the update and..

**Comment by SirLich** [comment]
Creative-mode flying mode faster?

**Comment by SirLich** [comment]
Minecraft type_family now takes a new format which includes a seperate "family" array. Is this part of an update to make all components object-types?

**Comment by SirLich** [comment]
Components no longer require "value" arguments.

**Comment by SirLich** [comment]
https://feedback.minecraft.net/hc/en-us/articles/360044928311-Minecraft-Nether-Update-1-16-0-Bedrock-

**Comment by jyooru** [comment]
New server called Galaxite
(currently not open to the public, but you can see that people are on)

**Comment by DevilLord41** [comment]
New entity component in 1.16
minecraft:admire_item
minecraft:barter
minecraft:behavior.admire_item
minecraft:behavior.avoid_block
minecraft:behavior.barter
minecraft:behavior.equip_item
minecraft:behavior.rise_to_liquid_level
minecraft:custom_hit_test
minecraft:lava_movement
minecraft:npc

**Comment by DevilLord41** [comment]
New Filters in 1.16
has_container_open
has_ranged_weapon
in_nether
inactivity_timer
is_persistent
light_level
random_chance
surface_mob

is_weather deprecated changed to `weather`

**Comment by KaiFireborn** [comment]
> recipes are out of experimtal

Same as blocks, items - out of [EX] and available on Realms. Most likely feature rules, features and structures too, but cannot confirm.

**Comment by JannisX11** [comment]
"loop" attribute of client side animations has new option `"hold_on_last_frame"`

**Comment by Jbenisek** [comment]
The component minecraft:damage_sensor will not be added to this entity as it won't work unless the format version is 1.15 or greater.

**Comment by Jbenisek** [comment]
22:18:09[Geometry][error]-Error: locator armor_offset.default_neck already exists with different values - using existing locator?   offset:0.000000,0.437500,0.000000 vs 0.000000,52.000000,0.000000


22:18:09[Geometry][error]-Error: locator armor_offset.default_neck already exists with different values - using existing locator?   offset:0.000000,0.437500,0.000000 vs 0.000000,52.000000,0.000000


22:18:09[Geometry][error]-Error: locator armor_offset.default_neck already exists with different values - using existing locator?   offset:0.000000,0.437500,0.000000 vs 0.000000,52.000000,0.000000


22:18:11[Geometry][error]-minecraft:player | minecraft:player | Locator: Error: model already has a locator armor_offset.default_neck that doesn't exactly match the one wanting to be added - skipping new definition in default(geometry.humanoid.custom)

**Comment by jyooru** [comment]
> 1. Check your ping to a server, thats how much time you have
> 2. Go on that server
> 3. You have to press e twice within your ping, see step 1
> 4. Minecraft crashes
>    I literally only just downloaded the update and..

This is actually an issue to do with The Hive caused by 1.16 and probably shouldn't be included.

**Comment by seriousa1** [comment]
on_interact with ridden entities is broken. 
Looking into why, and if its a formatting change or a bug
----
Update = confirmed broken rider_can_interact isn't functioning. 
seems to be in the 1.16.2 hotfix as far as I can tell, still investigating, reporting bug.

**Comment by Jbenisek** [comment]
(using the new 1.16 hitbox system) is this referring to minecraft:custom_hit_test?

**Comment by SirLich** [comment]
Addrider with Behavior Pack animations is broken.

**Comment by andreeich** [comment]
> 22:18:09[Геометрия][ошибка]-Ошибка: локатор armor_offset.default_neck уже существует с другими значениями - используя существующий локатор? смещение:0.000000,0.437500,0.000000 против 0.000000,52.000000,0.000000
> 
> 22:18:09[Геометрия][ошибка]-Ошибка: локатор armor_offset.default_neck уже существует с другими значениями - используя существующий локатор? смещение:0.000000,0.437500,0.000000 против 0.000000,52.000000,0.000000
> 
> 22:18:09[Геометрия][ошибка]-Ошибка: локатор armor_offset.default_neck уже существует с другими значениями - используя существующий локатор? смещение:0.000000,0.437500,0.000000 против 0.000000,52.000000,0.000000
> 
> 22:18:11[Геометрия][ошибка]-minecraft:| игрока майнкрафт:| игрока Локатор: Ошибка: модель уже имеет локатор armor_offset.default_neck, который не совсем соответствует тому, который хочет быть добавлен - пропуск нового определения в default(geometry.humanoid.custom)

I have the same error. How did you solve it?

**Comment by SirLich** [comment]
@andreeich you can join the discord https://discord.gg/NGeNhZpvzV
