### ISSUE TITLE
Add doc on component group shenannigans

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#53]
Err
Yes
Components are split up into two categories: Setter components, and Serialized components.
Setter components are ONLY EVALUATED WHEN ADDED. Removing setter components does not have any functionality.
For example skin_id, variant, etc.
Serialized components have a removed functionality.
Things like is_baby or is_chested is a serialized.
Removing the component group will remove the functionality.
Setter components have a default value, like 0. Serialized components simply are not added, and therefor dont effect the entity.
This is complicated by the fact that you can add components on top of each other. This essentially calls the remove on the component
shanewolf38 (ping me)Today at 3:13 PM
What do you mean they don't exist?
SirLich [Please Ping]Today at 3:14 PM
For example scales can overide each other.
Now, its FURTHER complicated by the fact that some serialized components lazily implement their remove functionality.
Pathfinding/agro is specifically geared to fail when you remove the component. It will continue to agro unless tricked with a blank replacement of some kind.
More complicated is the fact that some components MUST be added in groups, and cannot be added in the components list. I assume this is cause the remove functionality wasn't implemented properly. Trade tables are in this category.
Now, in particular your question was about scale: I have some suspicion that scale is serialized as a stack, FILO.
shanewolf38 (ping me)Today at 3:16 PM
Trade tables.. wow intresting
What is FILO?
SirLich [Please Ping]Today at 3:16 PM
First In Last Out.
But you can test it.
Queue, sorry.
shanewolf38 (ping me)Today at 3:16 PM
Ah I gotcha
Yeah, what you said yesterday about the wiki article on this, that would be INCREDIBLY helpful
for a ton of people
Where did you learn all of this? Just testing?
SirLich [Please Ping]Today at 3:17 PM
Experience.
Its not documented anywhere.
shanewolf38 (ping me)Today at 3:17 PM
Very nice
SirLich [Please Ping]Today at 3:17 PM
You should try two experements for me
shanewolf38 (ping me)Today at 3:18 PM
yeah I will start testing stuff with all this new information
im sure I've been doing a lot of unnecessary things
SirLich [Please Ping]Today at 3:18 PM
1) Add scale 2 to the components list, and then add scale 0.5 to the group, then remove the group.
I'm curios if it goes to 1, or 0.5

**Comment by SirLich** [comment]
@SirLich I tested two scenarios. In one I had no scale component listed anywhere except my component group, and in the other I initialized it in comonents to 0.5. In the first one, when I added the component group (setting scale to 2.0), it scaled up and when removed scaled back down to 1.0 (only removed the component group, nothing else was added). In the second case it scaled from 0.5 to 2.0, then returned to 1.0 and remained doing the same thing upon adding and removing.

**Comment by SirLich** [comment]
Tested the exact same thing with minecraft:behavior.look_at_target (used look_distance to differentiate between the two and gave both priority 1) and got the same results; the behavior was completed removed in both cases. I also tried adding the behavior by default simply under components, and removing a group with containing that behavior (defined inside, not just blank) completely removed the behavior. Also tried a combination of putting it in components and 2 component groups, and received the same result at the end, completely removed.
I'm not going to test any more today, but it seems for the most part proved to me. Component groups are simply a listing of types, and when added it adds all components inside but does not remember the group in any way. And removing a component group removes all the serialized components inside.
I am going to perform one more test though with skin_id actually ;P
And very nice troy lol

**Comment by SirLich** [comment]
We have found a bug (1.16.200) for those interested or planning on using movement via the new /event command. I assume this applies to more than just the movement component.

If you try to add a group with movement behavior, in the player BP def file (ver 1.16.0), it will not apply. However, if you apply via environment_sensor it works fine.

WORKAROUND (for using /event)
Add a comp group with the movement behavior, and a separate comp with mark_variant, variant, skin_id etc..

Use environment_sensor to detect when the player has MV, V, or SI of some number, calling the event that applies the movement behavior from the environment sensor.

This way you can use /event (or you could tag or some other env sensor trigger) to apply the comp group that has movement successfully.

**Comment by IlkinQafarov** [comment]
ty
