### ISSUE TITLE
Page not building

### ISSUE THREAD

**Issue by SirLich** [SirLich/technical-bedrock#59]
`Your SCSS file assets/css/just-the-docs-dark.scss has an error on line 156: Undefined variable: "$feedback-color".`

**Comment by jyooru** [comment]
There is no such file in this repository, and the file in [just-the-docs](https://github.com/pmarsceill/just-the-docs/blob/master/assets/css/just-the-docs-dark.scss) only has 3 lines.
But that file does have an include, which would be worth looking into. I can't figure out what it is including though.

**Comment by jyooru** [comment]
See #64 
Now works for me using WSL.
